language: node_js
node_js:
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'
  - '11'

install:
  - npm install

script: npm run test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master