services:
  sdk:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace
    volumes:
      - ./:/workspace
    environment:
      - CMFT_REPOSITORY=${CMFT_REPOSITORY:-}
      - CMFT_APIKEY=${CMFT_APIKEY:-}
      - CMFT_DOCUMENT_ID=${CMFT_DOCUMENT_ID:-}
      - CMFT_DOCUMENT_ALIAS=${CMFT_DOCUMENT_ALIAS:-}
      - CMFT_ASSET_ID=${CMFT_ASSET_ID:-}
      - CMFT_PROXY_URL=${CMFT_PROXY_URL:-}
      - CMFT_DEBUG_TESTS=${CMFT_DEBUG_TESTS:-}
